[phases.setup]
aptPkgs = ["ffmpeg", "libvips-dev"]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r workers/requirements.txt",
  "cd workers && npm install"
]
