[phases.setup]
aptPkgs = ["ffmpeg", "libvips-dev"]
nixPkgs = ["python311", "python311Packages.pip", "nodejs"]

[phases.install]
cmds = [
  "python3 -m pip install -r workers/requirements.txt",
  "cd workers && npm install"
]
